# Generated by Django 3.1.3 on 2021-01-03 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resume_Details',
            new_name='Resume',
        ),
    ]
